version: '3.1'
services:
  mongodb:
    image: candis/mongo-replica-set
    command: docker run -d -p 27017:27017 -p 27018:27018 -p 27019:27019
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  redis: 
    image: redis
    ports:
      - 6379:6379    
volumes:
  data:
